import { IngredientCategory } from '../../ingredient_category/entities/ingredient_category.entities'; 
import { RecipeIngredient } from '../../recipe_ingredient/entities/recipe_ingredient.entities'; 
import { AccountPantryItem } from '../../account_pantry_item/entities/account_pantry_item.entities';
import {
  Entity,
  Column,
  PrimaryColumn, // Sử dụng PrimaryColumn vì id là CHAR(36)
  ManyToOne,
  JoinColumn,
  OneToMany,
} from 'typeorm';

@Entity('ingredients') // Ánh xạ tới bảng 'ingredients'
export class Ingredient {
  @PrimaryColumn({
    type: 'char',
    length: 36,
    comment: 'Ingredient UUID, generated by the application',
  })
  id: string; // UUID, bạn sẽ cần tự tạo giá trị này ở tầng service

  @Column({
    type: 'varchar',
    length: 255,
    nullable: false,
    name: 'name',
  })
  name: string; // Tên nguyên liệu

  @Column({
    type: 'text',
    nullable: true,
    name: 'image_url',
    comment: 'URL or path to the ingredient image',
  })
  imageUrl: string | null; // URL hình ảnh, có thể null

  @Column({
    type: 'int',
    nullable: true,
    name: 'category_id', // Cột khóa ngoại
  })
  categoryId: number | null;

  /**
   * Mối quan hệ Many-to-One với thực thể IngredientCategory.
   * Một nguyên liệu (Ingredient) thuộc về một danh mục (IngredientCategory).
   */
  @ManyToOne(
    () => IngredientCategory,
    (category) => category.ingredients, // Thuộc tính 'ingredients' trong IngredientCategory
    {
      nullable: true, // Cho phép nguyên liệu không thuộc danh mục nào
      onDelete: 'SET NULL', // Nếu danh mục bị xóa, category_id của nguyên liệu sẽ là NULL
    },
  )
  @JoinColumn({ name: 'category_id', referencedColumnName: 'id' }) // Liên kết cột category_id với id của IngredientCategory
  category: IngredientCategory | null; // Đối tượng danh mục, có thể null

  /**
   * Mối quan hệ One-to-Many với thực thể RecipeIngredient (bảng trung gian).
   * Một nguyên liệu (Ingredient) có thể xuất hiện trong nhiều công thức khác nhau.
   */
  @OneToMany(() => RecipeIngredient, (recipeIngredient) => recipeIngredient.ingredient)
  recipeIngredients: RecipeIngredient[]; // Mảng các bản ghi RecipeIngredient liên quan đến nguyên liệu này

  @OneToMany(() => AccountPantryItem, (pantryItem) => pantryItem.ingredient)
  accountPantryItems: AccountPantryItem[];
}