version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_cooking_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: homnaynaugiBE
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3306:3306"